TARGET:=nkmd_ddr3

dump: $(TARGET)_t.lxt
	gtkwave $(TARGET)_t.lxt &

runsim: $(TARGET)_t.lxt

.vvp.lxt:
	vvp $< -lxt2

$(TARGET)_t.vvp: $(TARGET).v $(TARGET)_t.v
	iverilog -DSIMULATION -o $@ $^

clean:
	@rm -f $(TARGET)_t.lxt $(TARGET)_t.vvp

.SUFFIXES: .lxt .vvp
.PHONY: dump runsim clean
