TARGET=ddr3_fb
IVFLAGS=-DSIMULATION -DNO_IP
DEPS=ddr3_fb.v lcdc.v

dump: $(TARGET)_t.lxt
	gtkwave $(TARGET)_t.lxt &

runsim: $(TARGET)_t.lxt

.vvp.lxt:
	vvp $< -lxt2

$(TARGET)_t.vvp: $(TARGET)_t.v $(DEPS)
	iverilog $(IVFLAGS) -o $@ $^

.SUFFIXES: .vvp .lxt

.PHONY: clean
clean:
	rm -f $(TARGET)_t.lxt $(TARGET)_t.vvp
