dump: mpemu_t.lxt
	gtkwave mpemu_t.lxt &

runsim: mpemu_t.lxt

.vvp.lxt:
	vvp $< -lxt2

mpemu_t.vvp: mpemu.v mpemu_t.v testdata/gen/mp_a.hex
	iverilog -o $@ mpemu{,_t}.v

testdata/gen/mp_a.hex: gen_random_mul.rb
	ruby gen_random_mul.rb

.SUFFIXES: .lxt .vvp
