dump: resampler_t.lxt
	gtkwave resampler_t.lxt &

runsim: resampler_t.lxt

.vvp.lxt:
	vvp $< -lxt2

resampler_t.vvp: resampler.v mpemu.v rom_firbank_half.v rom_firbank_441_480.v resampler_t.v
	iverilog -o $@ $^

.SUFFIXES: .lxt .vvp
