dump: resampler_t.lxt
	gtkwave resampler_t.lxt &

runsim: resampler_t.lxt

.vvp.lxt:
	vvp $< -lxt2

resampler_t.vvp: resampler.v mpemu.v rom_*.v ringbuf.v resampler_t.v
	iverilog -DNO_IP -o $@ $^

.SUFFIXES: .lxt .vvp
