TARGET=dmix
DEPS=dmix.v spdif_dai_varclk.v spdif_dai.v resampler.v dac_drv.v mpemu.v rom_*.v ringbuf.v dcm.v async_fifo.v

dump: $(TARGET)_t.lxt
	gtkwave $(TARGET)_t.lxt &

runsim: $(TARGET)_t.lxt

.vvp.lxt:
	vvp $< -lxt2

$(TARGET)_t.vvp: $(TARGET)_t.v $(DEPS)
	iverilog -o $@ $^

.SUFFIXES: .lxt .vvp
